name: Build macos project
on: [push]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  build_native:
    strategy:
      fail-fast: false
      matrix:
        include:
        - { os: macos-latest }

    name: "Build - ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3

    - name: "install_name_tool"
      run: | 
        install_name_tool -id @rpath/libwpiutil.dylib cc_import/libwpiutil.dylib
        install_name_tool -id @rpath/libwpinet.dylib  cc_import/libwpinet.dylib
        install_name_tool -id @rpath/libwpiutil.dylib cc_import/libwpinet.dylib

        install_name_tool -id @rpath/libwpiutil.dylib cc_library/libwpiutil.dylib
        install_name_tool -id @rpath/libwpinet.dylib  cc_library/libwpinet.dylib
        install_name_tool -id @rpath/libwpiutil.dylib cc_library/libwpinet.dylib

    - run: bazel build //... -k --copt=-Wno-deprecated-anon-enum-enum-conversion
    - run: bazel test //... -k --copt=-Wno-deprecated-anon-enum-enum-conversion
  
    # Debugging cc_import
    - name: "cc_import otool -L"
      run: otool -L ./bazel-bin/cc_import/wpiutil_test
      if: ${{ always() }}

    - name: "cc_import otool -l"
      run: otool -l ./bazel-bin/cc_import/wpiutil_test
      if: ${{ always() }}

    - name: "cc_import linker params"
      run: cat ./bazel-bin/cc_import/wpiutil_test-2.params
      if: ${{ always() }}

    - name: "cc_import manifest"
      run: cat ./bazel-bin/cc_import/wpiutil_test.runfiles_manifest
      if: ${{ always() }}

    - run:  DYLD_PRINT_LIBRARIES=1 ./bazel-bin/cc_import/wpiutil_test
      if: ${{ always() }}
  
    # Debugging cc_import
    - name: "cc_import otool -L"
      run: otool -L ./bazel-bin/cc_import/wpinet_test
      if: ${{ always() }}

    - name: "cc_import otool -l"
      run: otool -l ./bazel-bin/cc_import/wpinet_test
      if: ${{ always() }}

    - name: "cc_import linker params"
      run: cat ./bazel-bin/cc_import/wpinet_test-2.params
      if: ${{ always() }}

    - name: "cc_import manifest"
      run: cat ./bazel-bin/cc_import/wpinet_test.runfiles_manifest
      if: ${{ always() }}

    - run:  DYLD_PRINT_LIBRARIES=1 ./bazel-bin/cc_import/wpinet_test
      if: ${{ always() }}
  
    # Debugging cc_library
    - name: "cc_library otool -L"
      run: otool -L ./bazel-bin/cc_library/wpinet_test
      if: ${{ always() }}

    - name: "cc_library otool -l"
      run: otool -l ./bazel-bin/cc_library/wpinet_test
      if: ${{ always() }}

    - name: "cc_library linker params"
      run: cat ./bazel-bin/cc_library/wpinet_test-2.params
      if: ${{ always() }}

    - name: "cc_library manifest"
      run: cat ./bazel-bin/cc_library/wpinet_test.runfiles_manifest
      if: ${{ always() }}

    - run:  DYLD_PRINT_LIBRARIES=1 ./bazel-bin/cc_library/wpinet_test
      if: ${{ always() }}
  
    # Debugging cc_library
    - name: "cc_library otool -L"
      run: otool -L ./bazel-bin/cc_library/wpiutil_test
      if: ${{ always() }}

    - name: "cc_library otool -l"
      run: otool -l ./bazel-bin/cc_library/wpiutil_test
      if: ${{ always() }}

    - name: "cc_library linker params"
      run: cat ./bazel-bin/cc_library/wpiutil_test-2.params
      if: ${{ always() }}

    - name: "cc_library manifest"
      run: cat ./bazel-bin/cc_library/wpiutil_test.runfiles_manifest
      if: ${{ always() }}

    - run:  DYLD_PRINT_LIBRARIES=1 ./bazel-bin/cc_library/wpiutil_test
      if: ${{ always() }}

    # Debugging opencv
    - name: "opencv otool -L"
      run: otool -L ./bazel-bin/other_library_works/test
      if: ${{ always() }}

    - name: "opencv otool -l"
      run: otool -l ./bazel-bin/other_library_works/test
      if: ${{ always() }}

    - name: "opencv linker params"
      run: cat ./bazel-bin/other_library_works/test-2.params
      if: ${{ always() }}

    - name: "opencv manifest"
      run: cat ./bazel-bin/other_library_works/test.runfiles_manifest
      if: ${{ always() }}

    - run:  DYLD_PRINT_LIBRARIES=1 ./bazel-bin/other_library_works/test
      if: ${{ always() }}

